import test from "ava";
import { compareProjectModels } from "../temp/compare-project-models.js";

test("compare-project-models", async (t) => {
  const p1 = {
    config: {},
    clients: [
      {
        name: "main",
        routes: {
          name: "IndexPage",
          pageImportPath: null,
          layoutImportPath: null,
          placeholderImportPath: null,
          guardImportPath: null,
          urlPath: null,
          children: [
            {
              name: "IndexPage",
              pageImportPath: "@/client/main//pages/index-page.tsx",
              layoutImportPath: null,
              placeholderImportPath: null,
              guardImportPath: null,
              urlPath: "/",
              children: [],
            },
            {
              name: "DashboardGroup",
              pageImportPath: null,
              layoutImportPath: "@/client/main//pages/(dashboard)/dashboard-layout.tsx",
              urlPath: null,
              placeholderImportPath: null,
              guardImportPath: null,
              children: [
                {
                  name: "UsersPage",
                  pageImportPath: "@/client/main//pages/(dashboard)/users/users-page.tsx",
                  layoutImportPath: null,
                  placeholderImportPath: null,
                  guardImportPath: null,
                  urlPath: "/users",
                  children: [
                    {
                      name: "UserDetailsPage",
                      pageImportPath:
                        "@/client/main//pages/(dashboard)/users/[userId]/user-details-page.tsx",
                      layoutImportPath: null,
                      placeholderImportPath: null,
                      guardImportPath: null,
                      urlPath: "/users/:userId",
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              name: null,
              pageImportPath: null,
              layoutImportPath: null,
              placeholderImportPath: null,
              guardImportPath: null,
              urlPath: null,
              children: [
                {
                  name: "ContactPage",
                  pageImportPath: "@/client/main//pages/(public)/contact/contact-page.tsx",
                  layoutImportPath: null,
                  placeholderImportPath: null,
                  guardImportPath: null,
                  urlPath: "/contact",
                  children: [],
                },
                {
                  name: "FeaturesPage",
                  pageImportPath: "@/client/main//pages/(public)/features/features-page.tsx",
                  layoutImportPath: null,
                  placeholderImportPath: null,
                  guardImportPath: null,
                  urlPath: "/features",
                  children: [],
                },
                {
                  name: "LandingPage",
                  pageImportPath: "@/client/main//pages/(public)/landing/landing-page.tsx",
                  layoutImportPath: null,
                  placeholderImportPath: null,
                  guardImportPath: null,
                  urlPath: "/landing",
                  children: [],
                },
              ],
            },
          ],
        },
        htmlHash: 0x123456,
        envHash: 0x98ab24,
      },
    ],
  };

  const p2 = {
    config: {},
    clients: [
      {
        name: "main",
        routes: {
          name: "IndexPage",
          pageImportPath: null,
          layoutImportPath: null,
          placeholderImportPath: null,
          guardImportPath: null,
          urlPath: null,
          children: [
            {
              name: "IndexPage",
              pageImportPath: "@/client/main//pages/index-page.tsx",
              layoutImportPath: null,
              placeholderImportPath: null,
              guardImportPath: null,
              urlPath: "/",
              children: [],
            },
            {
              name: "DashboardGroup",
              pageImportPath: null,
              layoutImportPath: "@/client/main//pages/(dashboard)/dashboard-layout.tsx",
              placeholderImportPath: null,
              guardImportPath: null,
              urlPath: null,
              children: [
                {
                  name: "UsersPage",
                  pageImportPath: "@/client/main//pages/(dashboard)/users/users-page.tsx",
                  layoutImportPath: null,
                  placeholderImportPath: null,
                  guardImportPath: null,
                  urlPath: "/users",
                  children: [
                    {
                      name: "UserDetailsPage",
                      pageImportPath:
                        "@/client/main//pages/(dashboard)/users/[userId]/user-details-page.tsx",
                      layoutImportPath: null,
                      placeholderImportPath: null,
                      guardImportPath: null,
                      urlPath: "/users/:userId",
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              name: null,
              pageImportPath: null,
              layoutImportPath: null,
              placeholderImportPath: null,
              guardImportPath: null,
              urlPath: null,
              children: [
                {
                  name: "FeaturesPage",
                  pageImportPath: "@/client/main//pages/(public)/features/features-page.tsx",
                  layoutImportPath: null,
                  placeholderImportPath: null,
                  guardImportPath: null,
                  urlPath: "/features",
                  children: [],
                },
                {
                  name: "LandingPage",
                  pageImportPath: "@/client/main//pages/(public)/landing/landing-page.tsx",
                  layoutImportPath: null,
                  placeholderImportPath: null,
                  guardImportPath: null,
                  urlPath: "/landing",
                  children: [],
                },
              ],
            },
          ],
        },
        htmlHash: 0x123456,
        envHash: 0x98ab24,
      },
    ],
  };

  const p3 = {
    config: { vite: async () => ({}) },
    clients: [],
  };

  const p4 = {
    config: { firebase: { projects: {} } },
    clients: [
      {
        name: "admin",
        routes: {
          pageImportPath: "@/admin/client/pages/index-page.tsx",
          layoutImportPath: null,
          placeholderImportPath: null,
          guardImportPath: null,
          urlPath: "/",
          children: [],
        },
        htmlHash: 0xa88980,
        envHash: 0x88bc13,
      },
      {
        name: "external",
        routes: {
          name: "IndexPage",
          pageImportPath: null,
          layoutImportPath: null,
          placeholderImportPath: null,
          guardImportPath: null,
          urlPath: null,
          children: [
            {
              name: "IndexPage",
              pageImportPath: "@/external/client/pages/index-page.tsx",
              layoutImportPath: null,
              placeholderImportPath: null,
              guardImportPath: null,
              urlPath: "/",
              children: [],
            },
            {
              name: "DashboardGroup",
              pageImportPath: null,
              layoutImportPath: "@/external/client/pages/(dashboard)/dashboard-layout.tsx",
              placeholderImportPath: null,
              guardImportPath: null,
              urlPath: null,
              children: [
                {
                  name: "UsersPage",
                  pageImportPath: "@/external/client/pages/(dashboard)/users/users-page.tsx",
                  layoutImportPath: null,
                  placeholderImportPath: null,
                  guardImportPath: null,
                  urlPath: "/users",
                  children: [
                    {
                      name: "UserDetailsPage",
                      pageImportPath:
                        "@/external/client/pages/(dashboard)/users/[userId]/user-detail-page.tsx",
                      layoutImportPath: null,
                      placeholderImportPath: null,
                      guardImportPath: null,
                      urlPath: "/users/:userId",
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              name: null,
              pageImportPath: null,
              layoutImportPath: null,
              placeholderImportPath: null,
              guardImportPath: null,
              urlPath: null,
              children: [
                {
                  name: "ContactPage",
                  pageImportPath: "@/external/client/pages/(public)/contact/contact-page.tsx",
                  layoutImportPath: null,
                  placeholderImportPath: null,
                  guardImportPath: null,
                  urlPath: "/contact",
                  children: [],
                },
                {
                  name: "FeaturesPage",
                  pageImportPath: "@/external/client/pages/(public)/features/features-page.tsx",
                  layoutImportPath: null,
                  placeholderImportPath: null,
                  guardImportPath: null,
                  urlPath: "/features",
                  children: [],
                },
                {
                  name: "LandingPage",
                  pageImportPath: "@/external/client/pages/(public)/landing/landing-page.tsx",
                  layoutImportPath: null,
                  placeholderImportPath: null,
                  guardImportPath: null,
                  urlPath: "/landing",
                  children: [],
                },
              ],
            },
          ],
        },
        htmlHash: 0x654321,
        envHash: 0x0013fe,
      },
    ],
  };

  const p1p2Changes = compareProjectModels(p1, p2);
  const p1p3Changes = compareProjectModels(p1, p3);
  const p1p4Changes = compareProjectModels(p1, p4);
  const nullP4Changes = compareProjectModels(null, p4);

  t.deepEqual(p1p2Changes, [
    {
      type: "update-runtime-client-routes",
      clientName: "main",
      clientRoutes: {
        name: "IndexPage",
        pageImportPath: null,
        layoutImportPath: null,
        placeholderImportPath: null,
        guardImportPath: null,
        urlPath: null,
        children: [
          {
            name: "IndexPage",
            pageImportPath: "@/client/main//pages/index-page.tsx",
            layoutImportPath: null,
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: "/",
            children: [],
          },
          {
            name: "DashboardGroup",
            pageImportPath: null,
            layoutImportPath: "@/client/main//pages/(dashboard)/dashboard-layout.tsx",
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: null,
            children: [
              {
                name: "UsersPage",
                pageImportPath: "@/client/main//pages/(dashboard)/users/users-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/users",
                children: [
                  {
                    name: "UserDetailsPage",
                    pageImportPath:
                      "@/client/main//pages/(dashboard)/users/[userId]/user-details-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/users/:userId",
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            name: null,
            pageImportPath: null,
            layoutImportPath: null,
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: null,
            children: [
              {
                name: "FeaturesPage",
                pageImportPath: "@/client/main//pages/(public)/features/features-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/features",
                children: [],
              },
              {
                name: "LandingPage",
                pageImportPath: "@/client/main//pages/(public)/landing/landing-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/landing",
                children: [],
              },
            ],
          },
        ],
      },
    },
    {
      type: "update-client-sdk-routes",
      clients: [
        {
          name: "main",
          routes: {
            name: "IndexPage",
            pageImportPath: null,
            layoutImportPath: null,
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: null,
            children: [
              {
                name: "IndexPage",
                pageImportPath: "@/client/main//pages/index-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/",
                children: [],
              },
              {
                name: "DashboardGroup",
                pageImportPath: null,
                layoutImportPath: "@/client/main//pages/(dashboard)/dashboard-layout.tsx",
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: null,
                children: [
                  {
                    name: "UsersPage",
                    pageImportPath: "@/client/main//pages/(dashboard)/users/users-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/users",
                    children: [
                      {
                        name: "UserDetailsPage",
                        pageImportPath:
                          "@/client/main//pages/(dashboard)/users/[userId]/user-details-page.tsx",
                        layoutImportPath: null,
                        placeholderImportPath: null,
                        guardImportPath: null,
                        urlPath: "/users/:userId",
                        children: [],
                      },
                    ],
                  },
                ],
              },
              {
                name: null,
                pageImportPath: null,
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: null,
                children: [
                  {
                    name: "FeaturesPage",
                    pageImportPath: "@/client/main//pages/(public)/features/features-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/features",
                    children: [],
                  },
                  {
                    name: "LandingPage",
                    pageImportPath: "@/client/main//pages/(public)/landing/landing-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/landing",
                    children: [],
                  },
                ],
              },
            ],
          },
          htmlHash: 0x123456,
          envHash: 0x98ab24,
        },
      ],
    },
  ]);

  t.deepEqual(p1p3Changes, [
    { type: "remove-runtime-client", clientName: "main" },
    { type: "update-runtime-client-config", config: { vite: async () => ({}) }, clients: [] },
    { type: "update-client-sdk-routes", clients: [] },
  ]);

  t.deepEqual(p1p4Changes, [
    { type: "add-runtime-client", clientName: "admin" },
    {
      type: "update-runtime-client-routes",
      clientName: "admin",
      clientRoutes: {
        pageImportPath: "@/admin/client/pages/index-page.tsx",
        layoutImportPath: null,
        placeholderImportPath: null,
        guardImportPath: null,
        urlPath: "/",
        children: [],
      },
    },
    { type: "update-runtime-client-html", clientName: "admin" },
    { type: "update-runtime-client-env", clientName: "admin" },
    { type: "add-runtime-client", clientName: "external" },
    {
      type: "update-runtime-client-routes",
      clientName: "external",
      clientRoutes: {
        name: "IndexPage",
        pageImportPath: null,
        layoutImportPath: null,
        placeholderImportPath: null,
        guardImportPath: null,
        urlPath: null,
        children: [
          {
            name: "IndexPage",
            pageImportPath: "@/external/client/pages/index-page.tsx",
            layoutImportPath: null,
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: "/",
            children: [],
          },
          {
            name: "DashboardGroup",
            pageImportPath: null,
            layoutImportPath: "@/external/client/pages/(dashboard)/dashboard-layout.tsx",
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: null,
            children: [
              {
                name: "UsersPage",
                pageImportPath: "@/external/client/pages/(dashboard)/users/users-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/users",
                children: [
                  {
                    name: "UserDetailsPage",
                    pageImportPath:
                      "@/external/client/pages/(dashboard)/users/[userId]/user-detail-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/users/:userId",
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            name: null,
            pageImportPath: null,
            layoutImportPath: null,
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: null,
            children: [
              {
                name: "ContactPage",
                pageImportPath: "@/external/client/pages/(public)/contact/contact-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/contact",
                children: [],
              },
              {
                name: "FeaturesPage",
                pageImportPath: "@/external/client/pages/(public)/features/features-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/features",
                children: [],
              },
              {
                name: "LandingPage",
                pageImportPath: "@/external/client/pages/(public)/landing/landing-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/landing",
                children: [],
              },
            ],
          },
        ],
      },
    },
    { type: "update-runtime-client-html", clientName: "external" },
    { type: "update-runtime-client-env", clientName: "external" },
    { type: "remove-runtime-client", clientName: "main" },
    {
      type: "update-runtime-client-config",
      config: { firebase: { projects: {} } },
      clients: [
        {
          name: "admin",
          routes: {
            pageImportPath: "@/admin/client/pages/index-page.tsx",
            layoutImportPath: null,
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: "/",
            children: [],
          },
          htmlHash: 0xa88980,
          envHash: 0x88bc13,
        },
        {
          name: "external",
          routes: {
            name: "IndexPage",
            pageImportPath: null,
            layoutImportPath: null,
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: null,
            children: [
              {
                name: "IndexPage",
                pageImportPath: "@/external/client/pages/index-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/",
                children: [],
              },
              {
                name: "DashboardGroup",
                pageImportPath: null,
                layoutImportPath: "@/external/client/pages/(dashboard)/dashboard-layout.tsx",
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: null,
                children: [
                  {
                    name: "UsersPage",
                    pageImportPath: "@/external/client/pages/(dashboard)/users/users-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/users",
                    children: [
                      {
                        name: "UserDetailsPage",
                        pageImportPath:
                          "@/external/client/pages/(dashboard)/users/[userId]/user-detail-page.tsx",
                        layoutImportPath: null,
                        placeholderImportPath: null,
                        guardImportPath: null,
                        urlPath: "/users/:userId",
                        children: [],
                      },
                    ],
                  },
                ],
              },
              {
                name: null,
                pageImportPath: null,
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: null,
                children: [
                  {
                    name: "ContactPage",
                    pageImportPath: "@/external/client/pages/(public)/contact/contact-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/contact",
                    children: [],
                  },
                  {
                    name: "FeaturesPage",
                    pageImportPath: "@/external/client/pages/(public)/features/features-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/features",
                    children: [],
                  },
                  {
                    name: "LandingPage",
                    pageImportPath: "@/external/client/pages/(public)/landing/landing-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/landing",
                    children: [],
                  },
                ],
              },
            ],
          },
          htmlHash: 0x654321,
          envHash: 0x0013fe,
        },
      ],
    },
    {
      type: "update-client-sdk-routes",
      clients: [
        {
          name: "admin",
          routes: {
            pageImportPath: "@/admin/client/pages/index-page.tsx",
            layoutImportPath: null,
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: "/",
            children: [],
          },
          htmlHash: 0xa88980,
          envHash: 0x88bc13,
        },
        {
          name: "external",
          routes: {
            name: "IndexPage",
            pageImportPath: null,
            layoutImportPath: null,
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: null,
            children: [
              {
                name: "IndexPage",
                pageImportPath: "@/external/client/pages/index-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/",
                children: [],
              },
              {
                name: "DashboardGroup",
                pageImportPath: null,
                layoutImportPath: "@/external/client/pages/(dashboard)/dashboard-layout.tsx",
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: null,
                children: [
                  {
                    name: "UsersPage",
                    pageImportPath: "@/external/client/pages/(dashboard)/users/users-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/users",
                    children: [
                      {
                        name: "UserDetailsPage",
                        pageImportPath:
                          "@/external/client/pages/(dashboard)/users/[userId]/user-detail-page.tsx",
                        layoutImportPath: null,
                        placeholderImportPath: null,
                        guardImportPath: null,
                        urlPath: "/users/:userId",
                        children: [],
                      },
                    ],
                  },
                ],
              },
              {
                name: null,
                pageImportPath: null,
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: null,
                children: [
                  {
                    name: "ContactPage",
                    pageImportPath: "@/external/client/pages/(public)/contact/contact-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/contact",
                    children: [],
                  },
                  {
                    name: "FeaturesPage",
                    pageImportPath: "@/external/client/pages/(public)/features/features-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/features",
                    children: [],
                  },
                  {
                    name: "LandingPage",
                    pageImportPath: "@/external/client/pages/(public)/landing/landing-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/landing",
                    children: [],
                  },
                ],
              },
            ],
          },
          htmlHash: 0x654321,
          envHash: 0x0013fe,
        },
      ],
    },
  ]);

  t.deepEqual(nullP4Changes, [
    { type: "create-runtime" },
    { type: "add-runtime-client", clientName: "admin" },
    {
      type: "update-runtime-client-routes",
      clientName: "admin",
      clientRoutes: {
        pageImportPath: "@/admin/client/pages/index-page.tsx",
        layoutImportPath: null,
        placeholderImportPath: null,
        guardImportPath: null,
        urlPath: "/",
        children: [],
      },
    },
    { type: "update-runtime-client-html", clientName: "admin" },
    { type: "update-runtime-client-env", clientName: "admin" },
    { type: "add-runtime-client", clientName: "external" },
    {
      type: "update-runtime-client-routes",
      clientName: "external",
      clientRoutes: {
        name: "IndexPage",
        pageImportPath: null,
        layoutImportPath: null,
        placeholderImportPath: null,
        guardImportPath: null,
        urlPath: null,
        children: [
          {
            name: "IndexPage",
            pageImportPath: "@/external/client/pages/index-page.tsx",
            layoutImportPath: null,
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: "/",
            children: [],
          },
          {
            name: "DashboardGroup",
            pageImportPath: null,
            layoutImportPath: "@/external/client/pages/(dashboard)/dashboard-layout.tsx",
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: null,
            children: [
              {
                name: "UsersPage",
                pageImportPath: "@/external/client/pages/(dashboard)/users/users-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/users",
                children: [
                  {
                    name: "UserDetailsPage",
                    pageImportPath:
                      "@/external/client/pages/(dashboard)/users/[userId]/user-detail-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/users/:userId",
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            name: null,
            pageImportPath: null,
            layoutImportPath: null,
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: null,
            children: [
              {
                name: "ContactPage",
                pageImportPath: "@/external/client/pages/(public)/contact/contact-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/contact",
                children: [],
              },
              {
                name: "FeaturesPage",
                pageImportPath: "@/external/client/pages/(public)/features/features-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/features",
                children: [],
              },
              {
                name: "LandingPage",
                pageImportPath: "@/external/client/pages/(public)/landing/landing-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/landing",
                children: [],
              },
            ],
          },
        ],
      },
    },
    { type: "update-runtime-client-html", clientName: "external" },
    { type: "update-runtime-client-env", clientName: "external" },
    {
      type: "update-runtime-client-config",
      config: { firebase: { projects: {} } },
      clients: [
        {
          name: "admin",
          routes: {
            pageImportPath: "@/admin/client/pages/index-page.tsx",
            layoutImportPath: null,
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: "/",
            children: [],
          },
          htmlHash: 0xa88980,
          envHash: 0x88bc13,
        },
        {
          name: "external",
          routes: {
            name: "IndexPage",
            pageImportPath: null,
            layoutImportPath: null,
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: null,
            children: [
              {
                name: "IndexPage",
                pageImportPath: "@/external/client/pages/index-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/",
                children: [],
              },
              {
                name: "DashboardGroup",
                pageImportPath: null,
                layoutImportPath: "@/external/client/pages/(dashboard)/dashboard-layout.tsx",
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: null,
                children: [
                  {
                    name: "UsersPage",
                    pageImportPath: "@/external/client/pages/(dashboard)/users/users-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/users",
                    children: [
                      {
                        name: "UserDetailsPage",
                        pageImportPath:
                          "@/external/client/pages/(dashboard)/users/[userId]/user-detail-page.tsx",
                        layoutImportPath: null,
                        placeholderImportPath: null,
                        guardImportPath: null,
                        urlPath: "/users/:userId",
                        children: [],
                      },
                    ],
                  },
                ],
              },
              {
                name: null,
                pageImportPath: null,
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: null,
                children: [
                  {
                    name: "ContactPage",
                    pageImportPath: "@/external/client/pages/(public)/contact/contact-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/contact",
                    children: [],
                  },
                  {
                    name: "FeaturesPage",
                    pageImportPath: "@/external/client/pages/(public)/features/features-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/features",
                    children: [],
                  },
                  {
                    name: "LandingPage",
                    pageImportPath: "@/external/client/pages/(public)/landing/landing-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/landing",
                    children: [],
                  },
                ],
              },
            ],
          },
          htmlHash: 0x654321,
          envHash: 0x0013fe,
        },
      ],
    },
    {
      type: "update-client-sdk-routes",
      clients: [
        {
          name: "admin",
          routes: {
            pageImportPath: "@/admin/client/pages/index-page.tsx",
            layoutImportPath: null,
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: "/",
            children: [],
          },
          htmlHash: 0xa88980,
          envHash: 0x88bc13,
        },
        {
          name: "external",
          routes: {
            name: "IndexPage",
            pageImportPath: null,
            layoutImportPath: null,
            placeholderImportPath: null,
            guardImportPath: null,
            urlPath: null,
            children: [
              {
                name: "IndexPage",
                pageImportPath: "@/external/client/pages/index-page.tsx",
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: "/",
                children: [],
              },
              {
                name: "DashboardGroup",
                pageImportPath: null,
                layoutImportPath: "@/external/client/pages/(dashboard)/dashboard-layout.tsx",
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: null,
                children: [
                  {
                    name: "UsersPage",
                    pageImportPath: "@/external/client/pages/(dashboard)/users/users-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/users",
                    children: [
                      {
                        name: "UserDetailsPage",
                        pageImportPath:
                          "@/external/client/pages/(dashboard)/users/[userId]/user-detail-page.tsx",
                        layoutImportPath: null,
                        placeholderImportPath: null,
                        guardImportPath: null,
                        urlPath: "/users/:userId",
                        children: [],
                      },
                    ],
                  },
                ],
              },
              {
                name: null,
                pageImportPath: null,
                layoutImportPath: null,
                placeholderImportPath: null,
                guardImportPath: null,
                urlPath: null,
                children: [
                  {
                    name: "ContactPage",
                    pageImportPath: "@/external/client/pages/(public)/contact/contact-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/contact",
                    children: [],
                  },
                  {
                    name: "FeaturesPage",
                    pageImportPath: "@/external/client/pages/(public)/features/features-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/features",
                    children: [],
                  },
                  {
                    name: "LandingPage",
                    pageImportPath: "@/external/client/pages/(public)/landing/landing-page.tsx",
                    layoutImportPath: null,
                    placeholderImportPath: null,
                    guardImportPath: null,
                    urlPath: "/landing",
                    children: [],
                  },
                ],
              },
            ],
          },
          htmlHash: 0x654321,
          envHash: 0x0013fe,
        },
      ],
    },
  ]);
});
